version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: homecloud-postgres
    environment:
      POSTGRES_DB: homecloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme123}
    ports:
      - "5432:5432"
    volumes:
      # Persist database data to host
      - postgres_data:/var/lib/postgresql/data
    networks:
      - homecloud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # HomeCloud Relay Server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homecloud-server
    environment:
      PORT: 8080
      DATABASE_URL: jdbc:postgresql://postgres:5432/homecloud
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-changeme123}
      JWT_SECRET: ${JWT_SECRET:-changeme456}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      UPLOADS_DIR: /app/uploads
    ports:
      - "8080:8080"
    volumes:
      # Persist uploads and pairings
      - uploads_data:/app/uploads
    networks:
      - homecloud-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  homecloud-network:
    driver: bridge

